=== sofo4ka19/knu/5-semester/OOP/lab2/src/main/resources/Medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/medicine"
           xmlns="http://example.com/medicine"
           elementFormDefault="qualified">

    <xs:element name="Medicine">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Medicament" type="MedicamentType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="MedicamentType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Pharm" type="xs:string"/>
            <xs:element name="Group" type="GroupType"/>
            <xs:element name="Analogs" type="AnalogsType" minOccurs="0"/>
            <xs:element name="Versions" type="VersionsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="prescription" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:simpleType name="GroupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ANTIBIOTICS"/>
            <xs:enumeration value="PAINKILLERS"/>
            <xs:enumeration value="VITAMINS"/>
            <xs:enumeration value="SEDATIVES"/>
            <xs:enumeration value="ANTIVIRAL"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AnalogsType">
        <xs:sequence>
            <xs:element name="Analog" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VersionsType">
        <xs:sequence>
            <xs:element name="Version" type="VersionType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VersionType">
        <xs:sequence>
            <xs:element name="Type" type="xs:string"/> <xs:element name="Certificate" type="CertificateType"/>
            <xs:element name="Package" type="PackageType"/>
            <xs:element name="Dosage" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CertificateType">
        <xs:sequence>
            <xs:element name="Number">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z]{2}-\d{6}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="IssueDate" type="xs:date"/>
            <xs:element name="ExpirationDate" type="xs:date"/>
            <xs:element name="RegisteringOrganization" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PackageType">
        <xs:sequence>
            <xs:element name="Type" type="xs:string"/> <xs:element name="Quantity" type="xs:positiveInteger"/>
            <xs:element name="Price">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0.01"/>
                        <xs:fractionDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== sofo4ka19/knu/5-semester/OOP/lab2/src/main/resources/Medicine.xml
<?xml version="1.0" encoding="UTF-8"?>
<Medicine xmlns="http://example.com/medicine"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://example.com/medicine Medicine.xsd">

    <Medicament id="med01" prescription="true">
        <Name>Amoxicillin</Name>
        <Pharm>Darnitsa</Pharm>
        <Group>ANTIBIOTICS</Group>
        <Analogs>
            <Analog>Flemoxin</Analog>
            <Analog>Ospamox</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Type>Tablets</Type>
                <Certificate>
                    <Number>UA-555001</Number>
                    <IssueDate>2023-01-15</IssueDate>
                    <ExpirationDate>2026-01-15</ExpirationDate>
                    <RegisteringOrganization>MOZ Ukraine</RegisteringOrganization>
                </Certificate>
                <Package>
                    <Type>Box</Type>
                    <Quantity>20</Quantity>
                    <Price>145.50</Price>
                </Package>
                <Dosage>500 mg, 3 times a day</Dosage>
            </Version>
        </Versions>
    </Medicament>

    <Medicament id="med02" prescription="false">
        <Name>Ibuprofen</Name>
        <Pharm>Farmak</Pharm>
        <Group>PAINKILLERS</Group>
        <Analogs>
            <Analog>Nurofen</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Type>Capsules</Type>
                <Certificate>
                    <Number>EU-100999</Number>
                    <IssueDate>2022-05-20</IssueDate>
                    <ExpirationDate>2025-05-20</ExpirationDate>
                    <RegisteringOrganization>EMA</RegisteringOrganization>
                </Certificate>
                <Package>
                    <Type>Bottle</Type>
                    <Quantity>50</Quantity>
                    <Price>210.00</Price>
                </Package>
                <Dosage>400 mg, after meal</Dosage>
            </Version>
            <Version>
                <Type>Gel</Type>
                <Certificate>
                    <Number>UA-222333</Number>
                    <IssueDate>2021-08-10</IssueDate>
                    <ExpirationDate>2024-08-10</ExpirationDate>
                    <RegisteringOrganization>MOZ Ukraine</RegisteringOrganization>
                </Certificate>
                <Package>
                    <Type>Tube</Type>
                    <Quantity>1</Quantity>
                    <Price>95.00</Price>
                </Package>
                <Dosage>Apply to skin twice a day</Dosage>
            </Version>
        </Versions>
    </Medicament>

    <Medicament id="med03" prescription="false">
        <Name>Ascorbic Acid</Name>
        <Pharm>KyivVitamin</Pharm>
        <Group>VITAMINS</Group>
        <Analogs>
            <Analog>Vitamin C</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Type>Dragee</Type>
                <Certificate>
                    <Number>UA-777888</Number>
                    <IssueDate>2023-03-01</IssueDate>
                    <ExpirationDate>2028-03-01</ExpirationDate>
                    <RegisteringOrganization>MOZ Ukraine</RegisteringOrganization>
                </Certificate>
                <Package>
                    <Type>Jar</Type>
                    <Quantity>100</Quantity>
                    <Price>45.00</Price>
                </Package>
                <Dosage>1-2 dragees per day</Dosage>
            </Version>
        </Versions>
    </Medicament>

    <Medicament id="med04" prescription="false">
        <Name>Valerian Extract</Name>
        <Pharm>Arterium</Pharm>
        <Group>SEDATIVES</Group>
        <Analogs>
            <Analog>Relaxil</Analog>
            <Analog>Persen</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Type>Tablets</Type>
                <Certificate>
                    <Number>UA-123123</Number>
                    <IssueDate>2022-11-15</IssueDate>
                    <ExpirationDate>2027-11-15</ExpirationDate>
                    <RegisteringOrganization>MOZ Ukraine</RegisteringOrganization>
                </Certificate>
                <Package>
                    <Type>Blister</Type>
                    <Quantity>50</Quantity>
                    <Price>35.50</Price>
                </Package>
                <Dosage>1 tablet before sleep</Dosage>
            </Version>
        </Versions>
    </Medicament>

    <Medicament id="med05" prescription="true">
        <Name>Novirin</Name>
        <Pharm>Kyivmedpreparat</Pharm>
        <Group>ANTIVIRAL</Group>
        <Analogs>
            <Analog>Groprinosin</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Type>Tablets</Type>
                <Certificate>
                    <Number>PL-999000</Number>
                    <IssueDate>2023-09-01</IssueDate>
                    <ExpirationDate>2026-09-01</ExpirationDate>
                    <RegisteringOrganization>Polish Health Agency</RegisteringOrganization>
                </Certificate>
                <Package>
                    <Type>Box</Type>
                    <Quantity>40</Quantity>
                    <Price>250.00</Price>
                </Package>
                <Dosage>2 tablets 3 times a day</Dosage>
            </Version>
        </Versions>
    </Medicament>

    <Medicament id="med06" prescription="true">
        <Name>Analgin</Name>
        <Pharm>Darnitsa</Pharm>
        <Group>PAINKILLERS</Group>
        <Analogs>
            <Analog>Metamizole</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Type>Ampoules</Type>
                <Certificate>
                    <Number>UA-456456</Number>
                    <IssueDate>2020-02-20</IssueDate>
                    <ExpirationDate>2025-02-20</ExpirationDate>
                    <RegisteringOrganization>MOZ Ukraine</RegisteringOrganization>
                </Certificate>
                <Package>
                    <Type>Box</Type>
                    <Quantity>10</Quantity>
                    <Price>85.20</Price>
                </Package>
                <Dosage>Intramuscular injection</Dosage>
            </Version>
        </Versions>
    </Medicament>

</Medicine>
